name: Continous integration
on: [push, pull_request]
jobs:
  cs:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpcs
          extensions: xmlwriter
      - name: Test code style
        run: phpcs
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl
          coverage: pcov
          extensions: mbstring, curl, json, pdo-sqlite
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Run tests
        run: composer test -- --coverage-xml
      - name: Push code coverage
        run: |
          composer global require scrutinizer/ocular
          ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover "./tests/_output/coverage.xml"
